<a href="https://colab.research.google.com/github/htjb/deep-learning-with-jax/blob/main/numpy_vs_jax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import jax.numpy as jnp
import jax
import numpy as np

In [2]:
a_jnp = jnp.array(range(10))
a_np = np.array(range(10))
a_np[5], a_jnp[5]

(5, Array(5, dtype=int32))

In [3]:
a_np[5] = 100
a_np[5]

100

In [4]:
try:
  a_jnp[5] = 100
except TypeError as e:
  print(e)

'<class 'jaxlib.xla_extension.ArrayImpl'>' object does not support item assignment. JAX arrays are immutable. Instead of ``x[idx] = y``, use ``x = x.at[idx].set(y)`` or another .at[] method: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html


In [5]:
a_jnp = a_jnp.at[5].set(100)
a_jnp[5]

Array(100, dtype=int32)

Looking at out of bounds indexing

In [6]:
a_jnp = jnp.array(range(10))
a_jnp

Array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [7]:
a_jnp[42]

Array(9, dtype=int32)

In [8]:
a_jnp.at[42].get(mode='drop')

Array(-2147483648, dtype=int32)

In [9]:
a_jnp.at[42].get(mode='fill', fill_value=-1)

Array(-1, dtype=int32)

In [10]:
a_jnp.at[42].set(100)
a_jnp

Array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [11]:
a_jnp.at[42].set(100, mode='clip')

Array([  0,   1,   2,   3,   4,   5,   6,   7,   8, 100], dtype=int32)